config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    #omniauth_callbacks: 'users/omniauth_callbacks'
  }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/book_category.rb
class BookCategory < ApplicationRecord
end

app/models/common_status.rb
class CommonStatus < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :lockable,
         :recoverable, :rememberable, :validatable

  protected
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login).downcase
    where(conditions.to_h).
      where(["(lower(login) = :value OR lower(email) = :value)",{ value: login }]).first
  end
end

app/controllers/account_controller.rb
class AccountController < Devise::RegistrationsController

  def new
    super
  end

  def create
    build_resource(sign_up_params)
    resource.username = params[resource_name][:username]
    resource.email = params[resource_name][:email]
    if verify_rucaptcha?(resource) && resource.save
      sign_in(resource_name, resource)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:login, :email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #prepend_before_action :require_no_authentication, only: [:cancel]
  #skip_before_action :require_no_authentication, only: [:welcome]
  #skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def new
    super
  end

  def create
    resource = warden.authenticate!(scope: resource_name, recall: "#{controller_path}#new")
    sign_in(resource_name, resource)
    redirect_to root_path
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :require_no_authentication, only: [:cancel]
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    resource.login = params[resource_name][:login]
    resource.email = params[resource_name][:email]
    if verify_rucaptcha?(resource) && resource.save
      #sign_in(resource_name, resource)
      set_flash_message! :notice, :signed_up
      respond_with resource, location: after_sign_up_path_for(resource)
    #else
      #set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
      #expire_
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  prepend_before_action :require_no_authentication, only: [:cancel]
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title_tag(str)
    content_for :title, h("#{str} - NDS资源管理系统")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2018 NDS部门资源管理
    <br>Design by
    <a href="http://blog.csdn.net/luoyegufei129" target=_new>李亚中</a>
    </p>
</footer>

app/views/layouts/_menu.html.erb
<div class="bootstrap-admin-with-small-navbar">
  <nav class="navbar navbar-default navbar-inverse navbar-fixed-top " role="navigation">
    <div class="container">
      <div class="row">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Boot3Admin</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<%= root_path %>">首页</a></li>
            <li ><a href="#">关于我们</a></li>			  
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">管理事项<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">用户列表</a></li>
                <li><a href="#">图书管理</a></li>
                <li><a href="#">设备管理</a></li>
                <li><a href="#">资金管理</a></li>
                <li><a href="#">团建活动</a></li>
                <li><a href="#">生活社区</a></li>
                <li class="divider"></li>
                <li><a href="http://kq.navinfo.com", target="_blank">考勤管理平台</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="请输入内容">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">链接</a></li>
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">个人中心<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">设置</a></li>
                  <li><a href="#">个人资料</a></li>
                  <li><a href="#">账户中心</a></li>
                  <li class="divider"></li>
                  <li><%= link_to "退出", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><a href="<%=new_user_registration_path %>">注册</a></li>
              <li><a href="<%=new_user_session_path %>">登录</a></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "NDS资源管理系统" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= yield :stylesheets %>
  </head>

  <body>
    <%= render 'layouts/menu' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <%= yield %>
      <br/>
      <br/>
      <div class="container">
        <%= render "layouts/footer" %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= yield :javascripts %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="alert alert-block alert-danger">
    <a class="close" data-dismiss='alert' href="#">×</a>
    <div><strong>有 <%= target.errors.count %> 处问题导致无法提交:</strong></div>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<ul class="list-group list-group-flush">
  <%- if controller_name != 'sessions' %>
    <li class="list-group-itm"><%= link_to t("common.login"), new_session_path(resource_name) %></li>
  <% end -%>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <li class="list-group-item"><%= link_to t("common.sign_up"), new_registration_path(resource_name) %></li>
  <% end -%>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <li class="list-group-item"><%= link_to t("users.forget_password"), new_password_path(resource_name) %></li>
  <% end -%>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <li class="list-group-item"><%= link_to t("users.not_recieve_confirm_mail"), new_confirmation_path(resource_name) %></li>
  <% end -%>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <li class="list-group-item"><%= link_to t("users.not_recieve_unlock_mail"), new_unlock_path(resource_name) %></li>
  <% end -%>
</ul>